version: '3'
services:
    nodejs-server:
        build:
            context: .
            dockerfile: node.dockerfile
    nginx-static-files:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - '8080:80'
