apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-static-files
  name: nginx-static-files
spec:
  replicas: 20
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-static-files
    spec:
      containers:
      - image: grod220/tms-nginx
        name: nginx-static-files
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
